title: Zhangqi Chang's Homepage
page-top-title: Zhangqi Chang
top-section-bg-text: Master of Science in Convergence Technology
home-subtitle: Zhangqi Chang&ensp;|&ensp;常张琦
copyright-text: '&copy; Zhangqi 2024-2025. All Rights Reserved.'
